### PR TITLE
Add support for other methods than GET and POST to ajax-lite.

### PR DESCRIPTION
**Pull request by mdiin**
I am in the situation that I need to submit a PUT request with sente, and I noticed that it isn't supported. I think would make sense to support the usual suspects here in encore, so I am starting this PR both as a discussion on how to support the query parameters for the remaining request types, and to add support for PUT.

Request types that make sense to support:

- GET (__done__)
- POST (__done__)
- PUT (this PR)
- DELETE
- PATCH (maybe?)
- HEAD

There are a couple of questions here:

1. Do you want PATCH to be supported? I don't see why not, but maybe there is a reason.
2. How to handle query parameters for DELETE and PATCH? I assume it is the same as for POST and PUT, but I am not definitely sure.

What are your thoughts?

### CODE REVIEW

**Comment by ptaoussanis** [comment]
Hi Matthias,

Sure - I'd be open to a PR that adds one or more of the remaining request types. And you're correct that this'd be the correct place to do it.

I don't normally use anything but GET and POST myself though - could you possibly confirm that the other methods would operate correctly with a simple mod to the `method*` case? It'd surprise me if that's _not_ the case, but a quick check against the HTTP spec should help confirm.

Thanks, cheers! :-)

**Comment by mdiin** [comment]
Thanks for the feedback! :-)

I think I will leave out PATCH, since I never use it and it isn't in the spec (?).

It seems to me that the [specification](http://www.w3.org/Protocols/HTTP/1.1/rfc2616bis/draft-lafon-rfc2616bis-03.html#POST) doesn't really specify whether to send request bodies or query strings, but in my experience both are possible.

I will look more into this later.

**Comment by ptaoussanis** [comment]
Sure, I'll leave it to your best judgement. Just let me know when you're ready for a merge. Cheers! :-)

**Comment by mdiin** [comment]
Just want to let you know I haven't forgotten this, I am just a little swamped at work right now.

**Comment by ptaoussanis** [comment]
No problem (or rush), take your time :-)

**Comment by mdiin** [comment]
Hey, just a heads-up. If you feel like it, I think you should merge this, since I won't get the time to investigate the remaining methods properly any time soon.

Sorry about the delay in getting back to you.

**Comment by ptaoussanis** [comment]
Done, thanks Matthias!

**Pull request merged**
